#!C:\Users\User\Desktop\N.E.M.O.S\N.E.M.O.S\N.E.M.O.S\envNemos\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
